//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Is_Takıp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        public int ID { get; set; }
        public string Firma_Unvan { get; set; }
        public string Yetkili { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Sektör { get; set; }
        public string Adres { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
    }
}
